### ISSUE TITLE
pkl file missing

### ISSUE THREAD

**Issue by djx2726889** [Applied-Machine-Learning-Lab/MMMLP#2]
Hello! In the line https://github.com/Applied-Machine-Learning-Lab/MMMLP/blob/b8565f4557df8c0f4f5f4c6655c8b362e81d017b/mmmlp.py#L138, it seems that the files 1m_text.pkl and 1m_image.pkl are required. Would you be able to share them?

**Comment by LongChen-l** [comment]
Have you get this file?

**Comment by Andy3117006664** [comment]
Thank you for bringing this to our attention. Unfortunately, we are unable to upload the files 1m_text.pkl and 1m_image.pkl due to their large size. These files contain raw text and image data, which can be quite large in terms of storage requirements. Therefore, it is not feasible to include them in the repository.
However, you can obtain the necessary data by crawling public datasets with text and image data. By doing so, you will be able to retrieve the required text and image data and use it in conjunction with the code.

**Comment by LongChen-l** [comment]
已收到！
